name    'aggressivex-java'
version '1.0.0'
author  'Luis M. Hdez'
license 'MIT'
project_page 'http://opensource.aggressivex.com/puppet/java'
source  'https://github.com/aggressivex/puppet-java'
summary 'Puppet module for oracle java setup'
description 'This module installs and manages oracle java.'